const Brand = [
  'Huawei',
  'Algebratec',
  'Tawasal',
  'Carrefour',
  'Dubai Police',
  'Reel Cinemas',
  'Dubai Sports',
  'Emirates',
  'Steppi',
  'Visit Abudhabi',
  'Approcks',
  'USeePay',
  'Anghami',
  'Road and Transport Authority',
  'Dasman Diabetes Institute',
  'Islamic Affairs and Charitable Activities Department',
  'ADCB',
  'MegTech',
  'UAE Ministry of Interior',
  'CNBC Arabia',
  'Arab News',
  'Nusuk',
  'Saudi Research and Media Group',
  'Lovin Dubai',
] as const;

export type BrandType = (typeof Brand)[number];
