export const Technology = [
  'Android',
  'HarmonyOS',
  'Kotlin',
  'Java',
  'React-Native',
  'Huawei Mobile Services (HMS)',
  'Firebase',
  'JavaScript',
  'CSS',
  'HTML',
  'Laravel',
  'PHP',
  'Node.js',
  'Next.js',
  'Express.js',
  'Google Play Services',
  'Photoshop',
  'Linux',
  'WordPress',
  'MUI',
  'Angular',
  'WooCommerce',
  'TypeScript',
  'MongoDB',
  'React',
  'Jetpack Compose',
  'Spring Boot',
  'Tailwind CSS',
] as const;
export type TechnologyType = (typeof Technology)[number];
