export const Technology = [
  'Android',
  'HarmonyOS',
  'Kotlin',
  'Java',
  'React-Native',
  'Huawei Mobile Services (HMS)',
  'Firebase',
  'JavaScript',
  'CSS',
  'HTML',
  'Laravel',
  'PHP',
  'Node.js',
  'Next.js',
  'Express.js',
  'Google Play Services',
  'Photoshop',
  'Linux',
  'WordPress',
  'MUI',
  'Angular',
  'WooCommerce',
  'TypeScript',
  'MongoDB',
  'React',
  'Jetpack Compose',
  'Spring Boot',
  'Tailwind CSS',
  'Swift',
  'ApkTool',
  'JADX',
  'SwiftUI',
  'ArkTS',
  'ArkUI',
  'Huawei Wear Engine',
  'Wearables',
  'Figma',
  'SDK Integration',
  'Android-to-Watch Sync',
  'Partner Delivery',
  'HMS',
  'React Native',
  'GMS Compatibility',
  'Apktool',
] as const;
export type TechnologyType = (typeof Technology)[number];
